:app:
  :host: resa.af83.com
:locations:
  :cuisine:
    :name: 'Cuisine'
    :color: '#a3d03d'
  :bas:
    :name: 'Salle du bas'
    :color: '#e734a0'
  :haut:
    :name: 'Salle du haut'
    :color: '#8d3c98'
:calendar:
  :server: './public/'
  :reservations: 'reservation.ics'
  :test: 'tests.ics'
  :name: 'export.ics'
