:app:
  :host: resa.af83.com
:locations:
  :cuisine:
    :name: 'Cuisine'
    :color: '#dc322f'
  :bas:
    :name: 'Salle du bas'
    :color: '#268bd2'
  :haut:
    :name: 'Salle du haut'
    :color: '#2aa198'
:calendar:
  :server: './public/'
  :reservations: 'reservation.ics'
  :test: 'tests.ics'
  :name: 'export.ics'
